### ISSUE TITLE
Missing dependecies hello-pangea/dnd

### ISSUE THREAD

**Issue by DrZanuff** [christopher-caldwell/react-kanban#19]
I've just finished porting the asseinfo branch with thiis branch. Good job guys. But when I tried to run the project after instaled it using yarn, Vite could not compile it, saying the https://github.com/hello-pangea/dnd  is missing. After installing locally it solved the issue. But could we add as dependencie for this project?

**Comment by christopher-caldwell** [comment]
Hello, it's listed [here](https://github.com/christopher-caldwell/react-kanban/blob/9c400ae536f193a2f4b7647c087b85d444e1d962/package.json#L26) as a peer dependency. 

I chose not to make it a dependency because that would require pinning a specific version of `@hello-pangea/dnd`, which wouldn't be best for people already using a different version. 

Unfortunately, that does mean you have to install the dependency yourself.
